import { atWeek } from './lib/format'
import type {
  Article,
  ChatMessage,
  DiaryEntry,
  Exercise,
  FeedbackItem,
  Lesson,
  MoveRequest,
  Notice,
  Place,
  Plan,
  Slot,
  Student,
} from './types'

export const STUDIO = {
  name: 'Resona',
  teacher: 'Адель',
  teacherShort: 'АД',
  city: 'Санкт-Петербург',
  place: 'студия на Петроградке',
  tagline: 'Голос как инструмент — не как лотерея',
}

export const ME_STUDENT_ID = 'samarina'

export const PLACES: Place[] = [
  {
    id: 'petro',
    name: 'Петроградка',
    address: 'Санкт-Петербург, Каменноостровский пр., 26, 2 этаж',
    howTo:
      'М «Петроградская», 6 минут пешком по Каменноостровскому. Парадная справа от кофейни. Домофон 26, второй этаж, табличка Resona. Если опаздываете — напишите в чат, не звоните в соседние квартиры.',
  },
  {
    id: 'vasil',
    name: 'Васильевский',
    address: 'Санкт-Петербург, 6-я линия В.О., 21, двор',
    howTo:
      'М «Василеостровская», выход к 6-й линии. Двор со стороны Среднего проспекта, код 2108. Кабинет во флигеле, вторая дверь.',
  },
  {
    id: 'online',
    name: 'Онлайн',
    address: 'Zoom, ссылка за 15 минут',
    online: true,
    howTo:
      'Ссылка приходит в уведомлении за 15 минут. Наушники обязательны. Комната без эха, камера на уровень глаз. Телефон на столе, не в руке.',
  },
]

/** Рабочие окна педагога: из них вычитаются занятые уроки и получаются свободные слоты. */
export const SLOTS: Slot[] = [
  { id: 'w1', weekday: 1, from: '17:00', to: '21:00', locationId: 'petro' },
  { id: 'w2', weekday: 2, from: '17:00', to: '21:00', locationId: 'petro' },
  { id: 'w3', weekday: 3, from: '17:00', to: '21:00', locationId: 'petro' },
  { id: 'w4', weekday: 4, from: '16:00', to: '20:00', locationId: 'vasil' },
  { id: 'w5', weekday: 5, from: '12:00', to: '16:00', locationId: 'petro' },
  { id: 'w6', weekday: 6, from: '11:00', to: '15:00', locationId: 'online' },
]

export const PLANS: Plan[] = [
  {
    id: 'trial',
    title: 'Пробный урок',
    lessons: 1,
    price: 2000,
    perLesson: 2000,
    hint: '45 минут: диагностика диапазона, опора, план на месяц',
  },
  {
    id: 'pack4',
    title: 'Абонемент 4',
    lessons: 4,
    price: 9200,
    perLesson: 2300,
    hint: 'Месяц точечной работы. Гибкий перенос за 12 часов',
  },
  {
    id: 'pack8',
    title: 'Абонемент 8',
    lessons: 8,
    price: 16800,
    perLesson: 2100,
    hint: 'Два месяца ритма. Домашние этюды и разбор песни',
    featured: true,
  },
  {
    id: 'pack12',
    title: 'Абонемент 12',
    lessons: 12,
    price: 22800,
    perLesson: 1900,
    hint: 'Сезон: техника, репертуар, сцена. Приоритет в расписании',
  },
]

export const STUDENTS: Student[] = [
  {
    id: 'samarina',
    name: 'Самарина Настя',
    callName: 'Настя',
    short: 'СН',
    voice: 'меццо',
    city: 'Санкт-Петербург',
    since: 'апрель 2026',
    planId: 'pack8',
    remaining: 3,
    used: 5,
    payment: 'paid',
    nextGoal: 'снять зажим в пассаже и довести «Laughing on the Outside» до сцены',
    rangeLow: 55,
    rangeHigh: 76,
    startLow: 57,
    startHigh: 72,
    skills: [
      { id: 'breath', label: 'Опора', value: 72 },
      { id: 'res', label: 'Резонанс', value: 58 },
      { id: 'legato', label: 'Легато', value: 64 },
      { id: 'mix', label: 'Микст', value: 41 },
      { id: 'dict', label: 'Дикция', value: 77 },
    ],
    repertoire: [
      { title: 'Laughing on the Outside', artist: 'Billie Holiday', status: 'в работе' },
      { title: 'Подмосковные вечера', artist: 'Соловьёв-Седой', status: 'разобрана' },
      { title: 'River', artist: 'Joni Mitchell', status: 'на очереди' },
    ],
    streak: 6,
    practiceWeek: [18, 22, 0, 25, 15, 20, 12],
  },
  {
    id: 'pasha',
    name: 'Паша',
    short: 'ПА',
    voice: 'баритон',
    city: 'Санкт-Петербург',
    since: 'январь 2026',
    planId: 'pack4',
    remaining: 1,
    used: 3,
    payment: 'paid',
    nextGoal: 'низ без продавливания, устойчивый A2',
    rangeLow: 45,
    rangeHigh: 67,
    startLow: 48,
    startHigh: 64,
    skills: [
      { id: 'breath', label: 'Опора', value: 61 },
      { id: 'res', label: 'Резонанс', value: 54 },
      { id: 'legato', label: 'Легато', value: 48 },
      { id: 'mix', label: 'Микст', value: 36 },
      { id: 'dict', label: 'Дикция', value: 70 },
    ],
    repertoire: [{ title: 'Fly Me to the Moon', artist: 'Bart Howard', status: 'в работе' }],
    streak: 2,
    practiceWeek: [10, 0, 12, 0, 8, 0, 0],
  },
  {
    id: 'alexandra',
    name: 'Александра',
    short: 'АЛ',
    voice: 'сопрано',
    city: 'Санкт-Петербург',
    since: 'июнь 2026',
    planId: 'pack12',
    remaining: 9,
    used: 3,
    payment: 'overdue',
    nextGoal: 'верх без крика, головной регистр на piano',
    rangeLow: 60,
    rangeHigh: 81,
    startLow: 62,
    startHigh: 76,
    skills: [
      { id: 'breath', label: 'Опора', value: 49 },
      { id: 'res', label: 'Резонанс', value: 63 },
      { id: 'legato', label: 'Легато', value: 55 },
      { id: 'mix', label: 'Микст', value: 28 },
      { id: 'dict', label: 'Дикция', value: 80 },
    ],
    repertoire: [{ title: 'Je veux vivre', artist: 'Gounod', status: 'этюд' }],
    streak: 4,
    practiceWeek: [20, 15, 20, 10, 0, 16, 0],
  },
  {
    id: 'maxim',
    name: 'Максим Курдиюмов',
    callName: 'Максим',
    short: 'МК',
    voice: 'тенор',
    city: 'Санкт-Петербург',
    since: 'март 2026',
    planId: 'pack8',
    remaining: 6,
    used: 2,
    payment: 'paid',
    nextGoal: 'снять горловую атаку на гласных «и» и «е»',
    rangeLow: 50,
    rangeHigh: 74,
    startLow: 52,
    startHigh: 69,
    skills: [
      { id: 'breath', label: 'Опора', value: 68 },
      { id: 'res', label: 'Резонанс', value: 50 },
      { id: 'legato', label: 'Легато', value: 44 },
      { id: 'mix', label: 'Микст', value: 39 },
      { id: 'dict', label: 'Дикция', value: 62 },
    ],
    repertoire: [{ title: 'Мой друг', artist: 'Высоцкий', status: 'в работе' }],
    streak: 3,
    practiceWeek: [12, 12, 12, 0, 14, 10, 0],
  },
  {
    id: 'anya',
    name: 'Аня',
    short: 'АН',
    voice: 'сопрано',
    city: 'Москва / онлайн',
    since: 'август 2026',
    planId: 'trial',
    remaining: 1,
    used: 0,
    payment: 'due',
    nextGoal: 'понять, с чего начинать: опора и комфортный центр',
    rangeLow: 59,
    rangeHigh: 74,
    startLow: 59,
    startHigh: 74,
    skills: [
      { id: 'breath', label: 'Опора', value: 20 },
      { id: 'res', label: 'Резонанс', value: 25 },
      { id: 'legato', label: 'Легато', value: 18 },
      { id: 'mix', label: 'Микст', value: 10 },
      { id: 'dict', label: 'Дикция', value: 55 },
    ],
    repertoire: [],
    streak: 0,
    practiceWeek: [0, 0, 0, 0, 0, 0, 0],
  },
  {
    id: 'katya',
    name: 'Катя Белова',
    callName: 'Катя',
    short: 'КБ',
    voice: 'альт',
    city: 'Санкт-Петербург',
    since: 'май 2026',
    planId: 'pack4',
    remaining: 4,
    used: 0,
    payment: 'paid',
    nextGoal: 'речевой уровень в пении, меньше «оперного» накрытия',
    rangeLow: 53,
    rangeHigh: 72,
    startLow: 55,
    startHigh: 70,
    skills: [
      { id: 'breath', label: 'Опора', value: 66 },
      { id: 'res', label: 'Резонанс', value: 71 },
      { id: 'legato', label: 'Легато', value: 60 },
      { id: 'mix', label: 'Микст', value: 47 },
      { id: 'dict', label: 'Дикция', value: 58 },
    ],
    repertoire: [{ title: 'Both Sides Now', artist: 'Joni Mitchell', status: 'разобрана' }],
    streak: 8,
    practiceWeek: [25, 20, 18, 22, 16, 20, 14],
  },
  {
    id: 'bugrova',
    name: 'Бугрова Настя',
    callName: 'Настя',
    short: 'БН',
    voice: 'сопрано',
    city: 'Санкт-Петербург',
    since: 'февраль 2026',
    planId: 'pack8',
    remaining: 5,
    used: 3,
    payment: 'paid',
    nextGoal: 'ровное легато на переходе и текст, который не разваливает опору',
    rangeLow: 57,
    rangeHigh: 79,
    startLow: 59,
    startHigh: 74,
    skills: [
      { id: 'breath', label: 'Опора', value: 64 },
      { id: 'res', label: 'Резонанс', value: 60 },
      { id: 'legato', label: 'Легато', value: 52 },
      { id: 'mix', label: 'Микст', value: 38 },
      { id: 'dict', label: 'Дикция', value: 74 },
    ],
    repertoire: [{ title: 'Someone Like You', artist: 'Adele', status: 'в работе' }],
    streak: 5,
    practiceWeek: [15, 18, 0, 20, 12, 0, 10],
  },
  {
    id: 'olesya',
    name: 'Олеся',
    short: 'ОЛ',
    voice: 'меццо',
    city: 'Санкт-Петербург',
    since: 'июль 2026',
    planId: 'pack4',
    remaining: 2,
    used: 2,
    payment: 'due',
    nextGoal: 'перестать подпирать звук горлом на громком',
    rangeLow: 54,
    rangeHigh: 73,
    startLow: 56,
    startHigh: 70,
    skills: [
      { id: 'breath', label: 'Опора', value: 44 },
      { id: 'res', label: 'Резонанс', value: 48 },
      { id: 'legato', label: 'Легато', value: 40 },
      { id: 'mix', label: 'Микст', value: 22 },
      { id: 'dict', label: 'Дикция', value: 66 },
    ],
    repertoire: [{ title: 'Кукушка', artist: 'Цой', status: 'в работе' }],
    streak: 2,
    practiceWeek: [12, 0, 10, 0, 0, 14, 0],
  },
  {
    id: 'albina',
    name: 'Альбина',
    short: 'АБ',
    voice: 'сопрано',
    city: 'Санкт-Петербург',
    since: 'октябрь 2025',
    planId: 'pack12',
    remaining: 7,
    used: 5,
    payment: 'paid',
    nextGoal: 'сцена: держать характер, а не только ноты',
    rangeLow: 60,
    rangeHigh: 83,
    startLow: 61,
    startHigh: 77,
    skills: [
      { id: 'breath', label: 'Опора', value: 78 },
      { id: 'res', label: 'Резонанс', value: 74 },
      { id: 'legato', label: 'Легато', value: 70 },
      { id: 'mix', label: 'Микст', value: 58 },
      { id: 'dict', label: 'Дикция', value: 82 },
    ],
    repertoire: [
      { title: 'Rolling in the Deep', artist: 'Adele', status: 'на сцену' },
      { title: 'Summertime', artist: 'Gershwin', status: 'разобрана' },
    ],
    streak: 11,
    practiceWeek: [30, 25, 20, 28, 22, 25, 18],
  },
  {
    id: 'irina',
    name: 'Ирина',
    short: 'ИР',
    voice: 'альт',
    city: 'Санкт-Петербург',
    since: 'сентябрь 2025',
    planId: 'pack8',
    remaining: 0,
    used: 8,
    payment: 'overdue',
    nextGoal: 'вернуть регулярность и добить второй куплет',
    rangeLow: 50,
    rangeHigh: 70,
    startLow: 52,
    startHigh: 67,
    skills: [
      { id: 'breath', label: 'Опора', value: 58 },
      { id: 'res', label: 'Резонанс', value: 62 },
      { id: 'legato', label: 'Легато', value: 56 },
      { id: 'mix', label: 'Микст', value: 34 },
      { id: 'dict', label: 'Дикция', value: 69 },
    ],
    repertoire: [{ title: 'Нежность', artist: 'Пахмутова', status: 'в работе' }],
    streak: 0,
    practiceWeek: [0, 0, 8, 0, 0, 0, 0],
  },
]

export function buildLessons(): Lesson[] {
  return [
    {
      id: 'l1',
      studentId: 'samarina',
      startsAt: atWeek(0, 18, 0),
      duration: 55,
      focus: 'Опора + пассаж',
      homework: 'Лип-трилль 4 мин, сирена на «у» в комфорте, куплет Holiday без форсирования верха',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l2',
      studentId: 'pasha',
      startsAt: atWeek(1, 19, 0),
      duration: 55,
      focus: 'Низ и речевой тон',
      homework: 'Чтение текста на одной высоте, затем та же фраза на мелодии',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l3',
      studentId: 'alexandra',
      startsAt: atWeek(2, 17, 30),
      duration: 55,
      focus: 'Головной регистр piano',
      homework: 'Гудение на «м» до D5, без вибрато «для красоты»',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l4',
      studentId: 'maxim',
      startsAt: atWeek(3, 18, 0),
      duration: 55,
      focus: 'Атака на гласных',
      homework: 'Стакато на «ха» + легато 5-тонка от A3',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l5',
      studentId: 'katya',
      startsAt: atWeek(4, 19, 0),
      duration: 55,
      focus: 'Резонанс маски',
      homework: 'Носовые сонанты + перевод в гласную без потери вибрации',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l6',
      studentId: 'samarina',
      startsAt: atWeek(5, 12, 0),
      duration: 55,
      focus: 'Разбор песни',
      homework: 'Записать куплет на телефон и отметить места, где пропадает опора',
      status: 'upcoming',
      locationId: 'petro',
    },
    {
      id: 'l7',
      studentId: 'anya',
      startsAt: atWeek(5, 14, 0),
      duration: 45,
      focus: 'Пробный урок',
      homework: '',
      status: 'upcoming',
      locationId: 'online',
    },
    {
      id: 'l8',
      studentId: 'pasha',
      startsAt: atWeek(6, 16, 0),
      duration: 55,
      focus: 'Репертуар',
      homework: '',
      status: 'upcoming',
      locationId: 'vasil',
    },
    {
      id: 'l9',
      studentId: 'samarina',
      startsAt: atWeek(0, 18, 0, 1),
      duration: 55,
      focus: 'Микст в пассаже',
      homework: '',
      status: 'upcoming',
      locationId: 'petro',
    },
    {
      id: 'l10',
      studentId: 'alexandra',
      startsAt: atWeek(2, 17, 30, 1),
      duration: 55,
      focus: 'Верх на piano',
      homework: '',
      status: 'upcoming',
      locationId: 'petro',
    },
    {
      id: 'l11',
      studentId: 'bugrova',
      startsAt: atWeek(1, 17, 0),
      duration: 55,
      focus: 'Легато на переходе',
      homework: 'Пятитонка на «о» от C4, по полтона вверх, без акцента на вершине',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l12',
      studentId: 'albina',
      startsAt: atWeek(2, 19, 0),
      duration: 55,
      focus: 'Сцена: характер фразы',
      homework: 'Спеть припев трём разным людям в голове, записать все три дубля',
      status: 'done',
      locationId: 'petro',
    },
    {
      id: 'l13',
      studentId: 'olesya',
      startsAt: atWeek(3, 17, 0),
      duration: 55,
      focus: 'Громкость без горла',
      homework: 'Речь на одной высоте в полный голос, потом та же фраза на мелодии',
      status: 'missed',
      locationId: 'vasil',
    },
    {
      id: 'l14',
      studentId: 'bugrova',
      startsAt: atWeek(1, 17, 0, 1),
      duration: 55,
      focus: 'Текст поверх легато',
      homework: '',
      status: 'upcoming',
      locationId: 'petro',
    },
    {
      id: 'l15',
      studentId: 'albina',
      startsAt: atWeek(2, 19, 0, 1),
      duration: 55,
      focus: 'Прогон программы',
      homework: '',
      status: 'upcoming',
      locationId: 'petro',
    },
    {
      id: 'l16',
      studentId: 'olesya',
      startsAt: atWeek(4, 12, 30),
      duration: 55,
      focus: 'Опора и тихий верх',
      homework: '',
      status: 'upcoming',
      locationId: 'petro',
    },
  ]
}

export const ARTICLES: Article[] = [
  {
    id: 'breath',
    title: 'Опора — это не «петь животом»',
    category: 'Дыхание',
    minutes: 6,
    lead: 'Опора — управление подсвязочным давлением. Живот сам по себе ничего не поёт.',
    body: [
      'Самый частый совет новичку — «дышите животом». Он не вредный, но неполный. Диафрагма опускается, рёбра расширяются, живот может податься вперёд — это вдох. Пение начинается на выдохе, и задача не «давить животом», а не дать клетке сразу схлопнуться.',
      'Опора ощущается как лёгкое сопротивление: воздух выходит медленно, звук не сипит и не кричит. Если давить сильнее, чем нужно связкам, появляется зажим и качок. Если отпускать слишком рано — звук садится, конец фразы пропадает.',
      'Практический тест: произнесите длинное «ссс», как шину спускаете. Где держится корпус? Рёбра не должны мгновенно падать. То же ощущение перенесите на гудение «ммм», затем на гласную.',
      'На уроке мы проверяем опору не зеркалом живота, а длиной фразы, ровностью динамик и тем, не краснеет ли шея. Если шея и челюсть работают вместо корпуса — опоры нет, есть компенсация.',
    ],
  },
  {
    id: 'res',
    title: 'Куда девается звук: резонаторы',
    category: 'Резонанс',
    minutes: 5,
    lead: 'Голос усиливается не «силой связок», а формой тракта. Связки задают тон, рот и носоглотка — тембр и громкость.',
    body: [
      'Грудной резонанс — ощущение вибрации в груди на низких и средних нотах. Это не отдельный орган, а костная проводимость. Гоняться за «грудным звуком» на верху — путь к форсированию.',
      'Маска — зона переносицы, скул, твёрдого нёба. Носовые согласные «м», «н» включают её почти автоматически. Ошибка — петь в нос. Правильный путь: найти вибрацию на сонанте и перевести её в гласную, не теряя ощущения.',
      'Рот — главный формирователь гласных. Слишком широкий зев на «а» даёт плоский звук, слишком узкий «у» — зажатый. Мы ищем форму, в которой гласная понятна и при этом не душит обертона.',
      'Если звук «внутри головы» и не летит — чаще всего зажата челюсть или корень языка. Сначала свобода, потом яркость. Яркость на зажиме — это крик с реверберацией.',
    ],
  },
  {
    id: 'vowels',
    title: 'Гласные: почему «и» срывается, а «а» орёт',
    category: 'Формирование',
    minutes: 7,
    lead: 'Каждая гласная — своя геометрия языка и губ. На высоте геометрию слегка меняют, смысл слова оставляют.',
    body: [
      'Русские гласные в пении живут иначе, чем в речи. На средней тесситуре можно петь почти разговорно. Чем выше нота, тем опаснее узкие гласные «и» и «е»: язык поднимается, тракт сужается, связки получают лишнюю нагрузку.',
      'Модификация — не «исказить слово», а открыть гласную ровно настолько, чтобы верх остался свободен. «И» чуть к «е», «е» чуть к «э», «а» не обязана быть самой широкой улыбкой в комнате.',
      'Упражнение: спойте одну высоту на «и-э-а-о-у» без смены опоры и без скачка челюсти. Если на «и» горло хватает — гласная слишком узкая или язык ушёл назад.',
      'В репертуаре сначала пойте мелодию на удобной гласной, затем верните текст. Слово не должно разрушать то, что уже получилось на вокализе.',
    ],
  },
  {
    id: 'passaggio',
    title: 'Пассаж: место, где голос «ломается»',
    category: 'Регистры',
    minutes: 6,
    lead: 'Переход между регистрами — не дефект. Дефект — пытаться протащить грудной механизм выше, чем он выдерживает.',
    body: [
      'У меццо переход часто лежит вокруг E4–F#4, у тенора выше, у баритона ниже. Цифры ориентир, не приговор: важнее, где именно у вас появляется давление, сип или вдруг «другой человек».',
      'Грубый приём — кричать грудью через пассаж. Короткий эффект, долгий отёк. Другой край — рано уходить в фальцет и терять плотность. Микст — это не «ни грудь, ни голова», а баланс: связки смыкаются, тракт не зажимается, громкость не обязана быть максимальной.',
      'Сирена на «у» или лип-трилль через переход — лучший диагноз. Если на одной ноте срыв, а на скольжении ровно — проблема не в ноте, а в резкой смене механизма.',
      'Не ставьте целью «убрать переход». Ставьте целью сделать его незаметным слушателю. Вы его всё равно будете чувствовать — и это нормально.',
    ],
  },
  {
    id: 'onset',
    title: 'Атака звука: три способа начать ноту',
    category: 'Техника',
    minutes: 4,
    lead: 'Как вы входите в звук, так часто и держите фразу. Жёсткая атака учит зажим, придыхательная — утечку.',
    body: [
      'Твёрдая атака: связки смыкаются до воздуха, потом взрыв. В речи это норма, в пении на постоянной основе сушит и даёт щелчок. Иногда нужна для характера — не как базовая привычка.',
      'Придыхательная: воздух раньше звука, «х» перед гласной. Полезно снять зажим, вредно как единственный режим — появляется шум, концы фраз разваливаются.',
      'Мягкая (сбалансированная): воздух и смыкание встречаются одновременно. Её и тренируем на стакато «ха» и на медленном filato.',
      'Если нота начинается с горлового удара — снимите согласную, пойте с дыхательного согласного, затем верните слово. Не лечите атаку громкостью.',
    ],
  },
  {
    id: 'hygiene',
    title: 'Гигиена голоса без мистики',
    category: 'Здоровье',
    minutes: 5,
    lead: 'Голос — слизистая и мышцы. Им нужны влажность, сон и отсутствие геройства на простуде.',
    body: [
      'Вода работает не за пять минут до выхода. Слизистая любит ровный питьевой режим в течение дня. Кофе и алкоголь сушат — не запрет, а повод пить ещё.',
      'Шёпот при осиплости — плохая идея: он часто сильнее нагружает, чем тихая речь. Если голос сел — говорите тихо, но звонко, или молчите.',
      'Разогрев нужен не «чтобы было». 6–8 минут сонантов и скольжений экономят связки лучше, чем сразу гнать песню в исходной тональности.',
      'Боль, резкий кашель после пения, потеря диапазона дольше пары дней — стоп и врач, не «ещё один урок через силу». Педагог не заменяет фониатра.',
    ],
  },
  {
    id: 'song',
    title: 'Как разобрать песню за четыре прохода',
    category: 'Репертуар',
    minutes: 5,
    lead: 'Песня ломается не из-за «нет голоса», а из-за того, что текст, ритм, мелодия и характер атакуют одновременно.',
    body: [
      'Проход 1 — речь. Проговорите текст в ритме, как монолог. Где не хватает воздуха в речи, в пении тем более не хватит. Поставьте дыхательные цезуры карандашом.',
      'Проход 2 — мелодия на удобной гласной, без слов. Найдите пассажи, скачки, ноты, которые просят модификации. Не геройствуйте в исходной тональности, если она пока враждебна.',
      'Проход 3 — слова на мелодии вполголоса. Следите, какие согласные сбивают опору: часто «р», стечения, финальные глухие.',
      'Проход 4 — характер. Динамика, пауза, к кому вы это поёте. Техника, которая не служит фразе, остаётся гимнастикой. Записывайте себя: ухо врёт, пока вы внутри звука.',
    ],
  },
]

export const EXERCISES: Exercise[] = [
  {
    id: 'hum',
    title: 'Гудение на «м»',
    minutes: 4,
    level: 'разогрев',
    description: 'Включает маску и смыкание без нагрузки на атаку. База почти каждого урока.',
    steps: [
      'Губы сомкнуты мягко, зубы не сжаты, язык лежит спокойно.',
      'На удобной середине гудите «ммм», как мурлыканье, не как зуммер.',
      'Следите, чтобы вибрация была в губах и переносице, а не в горле.',
      'Скользите на малую терцию вверх-вниз. Без форса и без пиано-шёпота.',
    ],
    targetMidi: 60,
  },
  {
    id: 'lip',
    title: 'Лип-трилль',
    minutes: 5,
    level: 'разогрев',
    description: 'Губной трелль снимает лишнее давление. Если губы не идут — слишком много воздуха или зажата челюсть.',
    steps: [
      'Щёки свободны, указательными пальцами можно слегка поддержать углы губ.',
      'Запустите моторчик и скользите сиреной по комфортному диапазону.',
      'Затем те же скольжения на пятитонке: вверх и вниз без остановок на нотах.',
      'Если моторчик срывается наверху — не давите, вернитесь и сузьте интервал.',
    ],
    targetMidi: 62,
  },
  {
    id: 'siren',
    title: 'Сирена на «у»',
    minutes: 4,
    level: 'регистры',
    description: 'Глитч через пассаж. Ищем ровную дорогу, а не красивую ноту.',
    steps: [
      'Возьмите тихое «у» внизу комфорта.',
      'Медленно скользите вверх, как сирена, без скачка тембра.',
      'В зоне перехода не прибавляйте громкость — наоборот, чуть уберите.',
      'Спуститесь тем же скольжением. Запомните место, где хотелось «переключить вручную».',
    ],
    targetMidi: 64,
  },
  {
    id: 'five',
    title: 'Пятитонка легато',
    minutes: 6,
    level: 'техника',
    description: '1-2-3-4-5-4-3-2-1 на одной гласной. Ровность важнее высоты.',
    steps: [
      'Стартуйте от удобной ноты (тюнер подскажет, обычно вокруг C4–D4).',
      'Пойте «о» или «у», все ноты одного размера, без акцентов на вершине.',
      'Челюсть почти не двигается. Движение — в воздухе и резонаторе.',
      'Поднимите тональность на полтона, пока звук остаётся таким же спокойным.',
    ],
    targetMidi: 62,
  },
  {
    id: 'stacc',
    title: 'Стакато на «ха»',
    minutes: 4,
    level: 'атака',
    description: 'Короткие импульсы учат смыкание без удара горлом.',
    steps: [
      'Лёгкое «ха» на одной ноте, как смешинки, не как кашель.',
      'Корпус даёт импульс, шея не участвует.',
      'Соберите 5 стакато + одно длинное легато на той же высоте.',
      'Если появляется щелчок — меньше согласной, больше воздуха в начале.',
    ],
    targetMidi: 60,
  },
  {
    id: 'speech',
    title: 'Речь → пение',
    minutes: 7,
    level: 'репертуар',
    description: 'Фраза из вашей песни сначала как речь, потом как мелодия. Снимает «оперный» налёт и театр ради театра.',
    steps: [
      'Выберите 1–2 такта текста.',
      'Проговорите в ритме, на удобной высоте, как человеку напротив.',
      'Повторите на мелодии, сохранив ту же позицию рта и ту же громкость речи.',
      'Только потом добавьте пение «как надо». Если пропала речь — рано.',
    ],
    targetMidi: 57,
  },
]

export const FEEDBACK_SEED: FeedbackItem[] = [
  {
    id: 'f1',
    studentId: 'samarina',
    createdAt: atWeek(0, 19, 10),
    rating: 5,
    energy: 4,
    clarity: 'Стало ясно, почему верх садился — я держала «и» слишком узко',
    text: 'После разбора пассажа песня наконец перестала быть набором трудных нот. Хочется ещё раз разобрать второй куплет медленно.',
  },
  {
    id: 'f2',
    studentId: 'pasha',
    createdAt: atWeek(1, 20, 5),
    rating: 4,
    energy: 3,
    clarity: 'Низ стал честнее, но я всё ещё давлю, когда хочется «по-мужски»',
    text: 'Формат с речью на одной ноте зашёл. Можно в следующий раз сразу взять бридж из стандарта?',
  },
  {
    id: 'f3',
    studentId: 'alexandra',
    createdAt: atWeek(2, 18, 40),
    rating: 5,
    energy: 5,
    clarity: 'Piano наверху — это не «петь слабее», а менять механизм. Дошло.',
    text: 'Было страшно звучать тихо. Спасибо, что не дали накрутить громкость.',
  },
  {
    id: 'f4',
    studentId: 'katya',
    createdAt: atWeek(4, 20, 0),
    rating: 5,
    energy: 4,
    clarity: 'Маска не равна носу — это я, кажется, всю жизнь путала',
    text: 'Домашние сонанты делаю каждый день, уже не скучно. Можно добавить разбор Both Sides Now целиком?',
  },
]

export const DIARY_SEED: DiaryEntry[] = [
  {
    id: 'd1',
    studentId: 'samarina',
    createdAt: atWeek(0, 19, 5),
    stars: 4,
    comment:
      'Пассаж стал честнее, когда убрали узкое «и». Дома — только лип-трилль и сирена, без геройства на Holiday.',
  },
  {
    id: 'd2',
    studentId: 'samarina',
    createdAt: atWeek(5, 13, 0),
    stars: 5,
    comment:
      'Куплет лёг в речь. Следующий урок: второй куплет и динамика без форса. Звёзды за работу, не за «красивый голос».',
  },
  {
    id: 'd3',
    studentId: 'pasha',
    createdAt: atWeek(1, 20, 0),
    stars: 3,
    comment: 'Низ есть, давление ещё привычка. Не петь «по-мужски» громче, чем говорит.',
  },
  {
    id: 'd4',
    studentId: 'alexandra',
    createdAt: atWeek(2, 18, 35),
    stars: 5,
    comment: 'Piano наверху получилось. Не возвращаться к крику «чтобы было слышно».',
  },
  {
    id: 'd5',
    studentId: 'albina',
    createdAt: atWeek(2, 20, 0),
    stars: 5,
    comment: 'Программа готова технически. Осталось перестать проверять себя ухом посреди фразы.',
  },
  {
    id: 'd6',
    studentId: 'bugrova',
    createdAt: atWeek(1, 18, 0),
    stars: 4,
    comment: 'Легато поехало ровно, пока без слов. Текст добавляем в следующий раз, не раньше.',
  },
  {
    id: 'd7',
    studentId: 'olesya',
    createdAt: atWeek(3, 18, 0),
    stars: 2,
    comment: 'Урок пропущен. Дома точно не стоит петь громко — вернёмся к речевому уровню.',
  },
]

export const NOTICES_SEED: Notice[] = [
  {
    id: 'n1',
    title: 'Квартирник 6 сентября',
    body: 'Суббота, 18:00, Петроградка. Два куплета максимум, без усилителя. Кто поёт — напишите мне в чат до четверга.',
    createdAt: atWeek(4, 10, 0),
  },
  {
    id: 'n2',
    title: 'Перенос кабинета в четверг',
    body: 'В этот четверг уроки на Васильевском: 6-я линия, 21, код 2108. Инструкция — в разделе «Кабинеты».',
    createdAt: atWeek(3, 9, 30),
  },
]

export const MOVES_SEED: MoveRequest[] = [
  {
    id: 'mv1',
    lessonId: 'l10',
    studentId: 'alexandra',
    proposedAt: atWeek(3, 18, 0, 1),
    comment: 'В среду не успеваю с работы, четверг удобнее.',
    status: 'pending',
    createdAt: atWeek(0, 9, 40),
  },
]

export const MESSAGES_SEED: ChatMessage[] = [
  {
    id: 'm1',
    studentId: 'samarina',
    from: 'student',
    text: 'Записала куплет дома. На «и» в третьей строчке опора уходит, слышно на записи.',
    createdAt: atWeek(3, 21, 10),
  },
  {
    id: 'm2',
    studentId: 'samarina',
    from: 'teacher',
    text: 'Слышу. Не тяните грудь наверх: «и» чуть к «е», громкость не прибавляйте. Разберём в пятницу.',
    createdAt: atWeek(3, 21, 40),
  },
  {
    id: 'm3',
    studentId: 'samarina',
    from: 'student',
    text: 'Поняла. И ещё: на квартирник могу Holiday, куплет и припев.',
    createdAt: atWeek(4, 10, 5),
  },
  {
    id: 'm4',
    studentId: 'maxim',
    from: 'student',
    text: 'На «и» в пятитонке снова хватает горло. Делать дальше или подождать урока?',
    createdAt: atWeek(4, 21, 0),
  },
  {
    id: 'm5',
    studentId: 'maxim',
    from: 'teacher',
    text: 'Не геройствовать. Вернитесь на «у», сузьте интервал. «И» — в среду на уроке.',
    createdAt: atWeek(4, 21, 20),
  },
  {
    id: 'm6',
    studentId: 'pasha',
    from: 'student',
    text: 'Адель, можно перенести четверг на час позже? Работа не отпускает.',
    createdAt: atWeek(2, 13, 0),
  },
  {
    id: 'm7',
    studentId: 'pasha',
    from: 'teacher',
    text: 'Да, 20:00 свободно. Переставила, посмотрите расписание.',
    createdAt: atWeek(2, 13, 25),
  },
]
